### ISSUE TITLE
The message clips if intro is added to appbar leading or action buttons

### ISSUE THREAD

**Issue by lohanidamodar** [tal-tech/flutter_intro#1]
Hi, thank you for the great package. I was trying it out to review it on my Youtube channel, however, when I added the intro keys to Appbar buttons (leading and drawer) the messages and buttons were clipped. Here I have attached the screenshots.

![Screenshot_1601459623](https://user-images.githubusercontent.com/6360216/94671689-ebd8c700-0333-11eb-9bf7-a6b6641e6673.png)
![Screenshot_1601460005](https://user-images.githubusercontent.com/6360216/94671696-ed09f400-0333-11eb-8aed-0152a09c45ef.png)

**Comment by hellohejinyu** [comment]
Hello, I have received your question, I will solve it as soon as possible.

**Comment by lohanidamodar** [comment]
@elowes I have not yet checked the code, but let me know if I can do anything to help.

**Comment by hellohejinyu** [comment]
My time zone is now midnight, and there is no computer around me. I have to wait to see the code this morning.

**Comment by lohanidamodar** [comment]
@elowes No problem, do it whenever suits you, thanks for the useful package.

**Comment by hellohejinyu** [comment]
@lohanidamodar https://github.com/tal-tech/flutter_intro#qa I added the setStepConfig and setStepsConfig methods in version 0.4.0 to solve this problem.
