### ISSUE TITLE
dispose

### ISSUE THREAD

**Issue by yvzoncu** [tal-tech/flutter_intro#10]
Can u check dispose again

**Comment by hellohejinyu** [comment]
```dart
WillPopScope(
    child: NeedAddStepWidget(xxx),
    onWillPop: () async {
        intro.dispose();
        return true;
    }
)
```

Is there any problem with writing like this

**Comment by yvzoncu** [comment]
Correct. I have tested and worked like that. So I think its worth renaming dispose with popScope or something else. Its a bit confusing like this. Again thanks for this great package.
