### ISSUE TITLE
大佬，自定义能给个最基础的demo吗

### ISSUE THREAD

**Issue by silentchild** [tal-tech/flutter_intro#13]
看了你的博文，已经手写实现了，但是还是感觉以后能使用你封装的插件会更方便，我试了一下，但是不会自定义界面，求写一个简单的demo

**Comment by hellohejinyu** [comment]
https://github.com/tal-tech/flutter_intro/blob/6beb2865b62f416f6240585add1ecf75ac04235f/lib/step_widget_builder.dart#L84-L159

看这里实现就好了，本质就是定义一个 `Widget Function(StepWidgetParams params)` 方法，然后这个方法返回的 Widget 会被渲染出来。

**Comment by silentchild** [comment]
多谢多谢，上午看到这个方法了，但是写错了没有成功，刚刚试了可以啦~~~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "何锦余"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 下午4:36
收件人: "tal-tech/flutter_intro"<flutter_intro@noreply.github.com&gt;; 
抄送: "分寸"<1051918608@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tal-tech/flutter_intro] 大佬，自定义能给个最基础的demo吗 (#13)





 
https://github.com/tal-tech/flutter_intro/blob/6beb2865b62f416f6240585add1ecf75ac04235f/lib/step_widget_builder.dart#L78-L160
 
看这里实现就好了，本质就是定义一个 Widget Function(StepWidgetParams params) 方法，然后这个方法返回的 Widget 会被渲染出来。

**Comment by silentchild** [comment]
大佬，某些步骤我只想下一步  不想高亮任何元素，这个怎么搞
