### ISSUE TITLE
大佬我又来了，能否增加一个参数把动画轨迹去掉啊

### ISSUE THREAD

**Issue by silentchild** [tal-tech/flutter_intro#14]
低端手机上卡卡的，感觉很诡异

**Comment by silentchild** [comment]
就是高亮部分移动的动画轨迹，给个参数控制一下吧，太卡了

**Comment by hellohejinyu** [comment]
```dart
Intro intro = Intro(
  noAnimation: true,
)
```
你好，加了个 `noAnimation` 参数

**Comment by silentchild** [comment]
> ```dart
> Intro intro = Intro(
>   noAnimation: true,
> )
> ```
> 
> 你好，加了个 `noAnimation` 参数

好的 谢谢大佬
