### ISSUE TITLE
Null operator error when going through the steps very quickly

### ISSUE THREAD

**Issue by lff5** [tal-tech/flutter_intro#18]
Hi.
In my app i have custom builder where all the messages are in one location (not flying around) thus i can go through the guide quite quickly (faster than `_animationDuration` per step). 

see `_onFinish()` function in `flutter_intro.dart`.
`_overlayEntry` is checked for not being null in the beginning of the function.
Now after Timer's `_animationDuration`, `_overlayEntry!` is not guaranteed to be non-null so it should be checked again.

#### Current code that crashes:
```
  void _onFinish() {
    if (_overlayEntry == null) return;
    _removed = true;
    _overlayEntry!.markNeedsBuild();
    Timer(_animationDuration, () {
      _overlayEntry!.remove();
      _overlayEntry = null;
    });
  }
```
#### Modified code that does not crash:
```
  void _onFinish() {
    if (_overlayEntry == null) return;
    _removed = true;
    _overlayEntry!.markNeedsBuild();
    Timer(_animationDuration, () {
      if (_overlayEntry != null) {
        _overlayEntry!.remove();
        _overlayEntry = null;
      }
    });
  }
```

**Comment by hellohejinyu** [comment]
Thank you very much, the 2.0.2 version has been released to solve this problem
