### ISSUE TITLE
Selected widget is darker than it should be

### ISSUE THREAD

**Issue by boroma4** [tal-tech/flutter_intro#19]
Hi,

Thanks for an amazing package!
I think I did everything like in the example, but the widget that is supposed to be highlighted is darker than it should be for some reason. The colors that should be there are much lighter.

![image](https://user-images.githubusercontent.com/52993491/112880377-087f6d00-90d3-11eb-9f2a-abf61f23290c.png)

Maybe you can suggest what is causing this? I am not experienced with color blending at all.

**Comment by hellohejinyu** [comment]
It may be because your Selected component has a display animation. When flutter intro obtains the position of the component according to the Globalkey, the component has not really been displayed, so it is not highlighted. You can try to see if adding a delay can solve the problem.

**Comment by boroma4** [comment]
Actually, the reason appeared to be a bit different.
The issue happened when the banner ad was on the screen during the intro, you can see from the demo below that something isn't right.
When I removed the banner ad from the screen, everything works perfectly.
Maybe this information is useful for you, but regardless I can resolve it on my side too.

![demo](https://user-images.githubusercontent.com/52993491/112956102-c8f36800-9148-11eb-8944-4cbab8ed6c03.gif)

Feel free to close this issue.

**Comment by hellohejinyu** [comment]
Okay, I'm glad you found a solution to your problem.

**Comment by hashirshoaeb** [comment]
I'm facing the same issue. Any reason why it's highlighted part gets dark?

https://user-images.githubusercontent.com/35165481/119669331-691bf380-be51-11eb-83b9-bd17dfd67766.mov

**Comment by boroma4** [comment]
@hashirshoaeb, I'd suggest starting with checking whether you have any widgets that re-render inside the scene (in my case, the banner ad). If possible, remove widgets one by one and see if the issue persists to isolate it.

**Comment by hashirshoaeb** [comment]
@boroma4 Thanks for a quick response. Should I look into the widgets inside the highlighted part or the whole screen in general?

**Comment by boroma4** [comment]
@hashirshoaeb I hadn't figured the root cause when I was dealing with this, so I can't tell for sure. If I got what you are saying correctly, then the whole screen (basically the whole area that gets dim, idk if things outside of it can cause the issue). I couldn't also reproduce it with anything except for the ad.
