### ISSUE TITLE
Feature: expose isOpen in the api

### ISSUE THREAD

**Issue by lff5** [tal-tech/flutter_intro#20]
Hi. 

I want to have Android's back button to work properly. 
Right now thats my code:

```
          if (Platform.isAndroid) {
            return WillPopScope(
              onWillPop: () async {
                intro.dispose();
                if (Navigator.of(context).canPop()) {
                  return true;
                }
             },);
          }
```

It does close the intro stepper but if the app navigation is on root level it also exits the app or moves back which is unintended. So i would need to have some feedback on whether intro was closed.
Either should intro.dispose() return if anything was closed or there should be isOpen function in the api. The last being much more universal for other purposes too.
Thank you!

**Comment by hellohejinyu** [comment]
Thank you for your suggestion, I will expose the api as soon as possible

**Comment by hellohejinyu** [comment]
https://github.com/tal-tech/flutter_intro/blob/fd13c3953b8c97ad08bacbfa511c888e939adbc6/example/lib/main.dart#L232-L241
Version `2.1.0` has just been released, and now you can execute the getStatus method to get the current status. Finally, thank you very much for your suggestions.
