### ISSUE TITLE
Allow tapping on the highlighted UI element

### ISSUE THREAD

**Issue by jagged91** [tal-tech/flutter_intro#23]
Hi, 

Great library. Could you add a VoidCallback for when a user taps on the highlighted UI element? Tapping to dismiss is OK but I want to let the user get through onboarding by actually tapping the buttons! Maybe another easier way would be to make the 'finish' callback available from the library.

**Comment by hellohejinyu** [comment]
https://github.com/tal-tech/flutter_intro/blob/6e993fc429d01604fd51670986b75509d754d213/example/lib/main.dart#L102-L107

Thank you for you advice. You can use `onHighlightWidgetTap` in `2.2.1`.

**Comment by jagged91** [comment]
@hellohejinyu Thank you! Note that in my custom tooltip widget builder I had to set HitTestBehavior.deferToChild for this to work!
