### ISSUE TITLE
[Feature Request] Would be nice to have Skip/Close option in StepWidgetBuilder.useDefaultTheme

### ISSUE THREAD

**Issue by absar** [tal-tech/flutter_intro#26]
First of all thank you for the awesome package.
I have a small default feature request, it would be nice to have Skip/Close button in **StepWidgetBuilder.useDefaultTheme**, as most of the use cases will need a Skip button, which is better than creating a custom widgetBuilder for most of the users.
It should have these options:
- StepWidgetBuilder.useDefaultTheme should have a parameter **showSkip** or **showFinish**
- skipButtonTextBuilder to customize it's text
- If it is the last index this should not be shown
- Should have optional parameters to pass text style and button style e.g. skipButtonTextStyle, skipButtonStyle

Same thing can be done for a **Previous** button, so that out-of-the-box the library provides easy customizations

**Comment by hellohejinyu** [comment]
https://github.com/tal-tech/flutter_intro/blob/764cdff8c266f3207c50e6da78d8538050fdaca8/example/lib/main.dart#L155-L191

Hello, I am very glad you pointed out this problem. After careful consideration, I think that adding too many properties to `useDefaultTheme` will increase the difficulty of use. So I added a `useAdvancedTheme` method to customize the style more freely. The final display of results as shown in the picture below.

![Kapture 2021-05-13 at 10 38 22](https://user-images.githubusercontent.com/8766034/118069789-6348fb80-b3d7-11eb-9774-0d0ecdfc060c.gif)

**Comment by absar** [comment]
Thank you very much for the prompt update. The new  `useAdvancedTheme` is even better
