### ISSUE TITLE
能否添加intro显示队列

### ISSUE THREAD

**Issue by zKidor** [tal-tech/flutter_intro#27]
你好，
这个插件真心不错，感谢！

我使用的时候遇到了一些问题:
我引导的步骤是分多个Intro，当符合Intro触发条件后再显示该条件下的Intro。
所以就可能导致一个Intro还没引导完，另一个Intro就start了，这时就会覆盖到没完成的Intro上面，导致错乱

现在的demo上，没找到结束监听，没办法知道上一个Intro是否处理完再处理下一个。能否添加一个队列或者一个结束的监听回调呢？

谢谢

**Comment by hellohejinyu** [comment]
你可以先调用前一个的`intro.dispose()`方法，然后延迟个400ms，再显示下一个 intro。这样应该可以的吧。

我是觉得这个东西加监听事件意义不大，不过确实可以考虑把引导页弄成支持动态新增的。但这个改动就会比较大一点，我后面弄一下，你先按照上面的应该是可以临时满足你的需求的。：）

**Comment by zKidor** [comment]
调用intro.dispose()，那前一个还没点完就没了

**Comment by hellohejinyu** [comment]
> 调用intro.dispose()，那前一个还没点完就没了

![Kapture 2021-05-14 at 15 52 14](https://user-images.githubusercontent.com/8766034/118239452-6376f300-b4cc-11eb-818f-6e083454be71.gif)

不会啊，你用`useAdvancedTheme`，这样可以自定义按钮的功能。
<img src="https://user-images.githubusercontent.com/8766034/118239571-886b6600-b4cc-11eb-8236-f4bc7ae4d303.png" width="400" />

**Comment by zKidor** [comment]
> > 调用intro.dispose()，那前一个还没点完就没了
> 
> ![Kapture 2021-05-14 at 15 52 14](https://user-images.githubusercontent.com/8766034/118239452-6376f300-b4cc-11eb-818f-6e083454be71.gif)
> 
> 不会啊，你用`useAdvancedTheme`，这样可以自定义按钮的功能。
> <img alt="" width="400" src="https://user-images.githubusercontent.com/8766034/118239571-886b6600-b4cc-11eb-8236-f4bc7ae4d303.png">

哦，明白你意思了，我以为是在另一个弹出来的时候调用前一个的dispose

**Comment by hellohejinyu** [comment]
[https://github.com/minaxorg/flutter_intro](https://github.com/minaxorg/flutter_intro) 3.0 版本我完全重写了，现在不要求在一开始就指定引导页的数量，直接通过 `IntroStepBuilder` 类绑定在组件上，这样就不用人为的去操作多个 intro 实例了。
