### ISSUE TITLE
Failed to find render object

### ISSUE THREAD

**Issue by akifarhan** [tal-tech/flutter_intro#30]
Hi, first of all I would like to thank for this super awesome package! 

Right now I'm stuck debugging this error `_CastError (Null check operator used on a null value)` to start the intro. After digging in, I found that it failed to get the `currentContext` from the global keys when trying to `_getWidgetInfo`.  May I know what are the possibilities that might cause this issue? 

I'm having this problem when I want to auto start the intro. There's no problem if I manually start it.

**Comment by hellohejinyu** [comment]
It should be that the component has not been rendered when the intro is started.

**Comment by akifarhan** [comment]
How to make sure that the components have been rendered? I can see that all the components with the intro keys have been rendered in the screen before the intro started.

**Comment by hellohejinyu** [comment]
I completely rewrote the 3.0 version and now IntroStepBuilder has an onWidgetLoad method on it that ensures the component renders.
