### ISSUE TITLE
Add a callback that runs when the user perform an action

### ISSUE THREAD

**Issue by wagner-rebello** [tal-tech/flutter_intro#33]
It would be cool if there is some callback that runs when the user press on next button or finish button.

We can change things on the screen like scroll position, sliver and expansion panels depending on the tutorial step the user is going to enter.

**Comment by hellohejinyu** [comment]
https://github.com/tal-tech/flutter_intro/blob/d1a0e23ee6a91377be7f54341c30c6202bcf8c4a/example/lib/main.dart#L177-L180

https://github.com/tal-tech/flutter_intro/blob/d1a0e23ee6a91377be7f54341c30c6202bcf8c4a/example/lib/main.dart#L245-L250

Maybe you can try `StepWidgetBuilder.useAdvancedTheme` or implement the widgetBuilder method yourself.
