### ISSUE TITLE
globalKey in intro.keys has forgotten to bind

### ISSUE THREAD

**Issue by ahmed-moha** [tal-tech/flutter_intro#36]
i'm facing that issues if anyone tell me how to solve it it will be great

**Comment by niels-hubs** [comment]
Yes, the plugin can't handle FutureBuilders, so dynamic content or you have to execute the tutorial after the data has loaded... which totally sucks.

**Comment by hellohejinyu** [comment]
I completely rewrote the 3.0 version, the fact that the 2.0 version required to declare a fixed number of guide pages at the beginning was really bad.
