### ISSUE TITLE
First step message does not disappear

### ISSUE THREAD

**Issue by OUDON** [tal-tech/flutter_intro#37]
Thank you for this awesome library.

When I use combine this library with `gen_l10n`, a first step message does not disappear.
There are any way to set messages from `context`?

### Code
```dart
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _startTutorial();
  }

  void _startTutorial() async {
    SharedPreferences pref = await SharedPreferences.getInstance();
    if (pref.getBool("showTutorial") ?? true == false) return;

    intro = Intro(
      stepCount: 6,
      maskClosable: true,
      widgetBuilder: StepWidgetBuilder.useDefaultTheme(
        texts: [
          AppLocalizations.of(context)!.tutorialSelectMusic,
          AppLocalizations.of(context)!.tutorialSetPointA,
          AppLocalizations.of(context)!.tutorialSetPointB,
          AppLocalizations.of(context)!.tutorialRepeatOn,
          AppLocalizations.of(context)!.tutorialSlide,
          AppLocalizations.of(context)!.tutorialAD,
        ],
        buttonTextBuilder: (currPage, totalPage) {
          return currPage < totalPage - 1
              ? AppLocalizations.of(context)!.tutorialButtonNext
              : AppLocalizations.of(context)!.tutorialButtonFinish;
        },
      ),
    );

    Timer(
      const Duration(
        milliseconds: 500,
      ),
      () {
        intro.start(context);
      },
    );
    pref.setBool("showTutorial", false);
  }
```

pubspec.yaml
```
dependencies:
  flutter_intro: ^2.3.1
```

### Screenshots

1st step. 
![1st step](https://user-images.githubusercontent.com/14174940/164886519-058a11d6-3c08-4517-b922-e1315bde0837.png)

2nd step. but 1st step message does not disappeared.
![2nd step](https://user-images.githubusercontent.com/14174940/164886532-1746be11-a876-4fef-8b7d-f6407881537e.png)

3rd step. 2nd step message disappeared, and 1st step message does not disappeared.
![3rd step](https://user-images.githubusercontent.com/14174940/164886535-01c135db-091a-4813-acb6-b757811c7049.png)

**Comment by OUDON** [comment]
I have solved this issue. Instead of direct approach, I decided to use `easy_localize` that can localize without `BuildContext`. Thank you.

**Comment by hellohejinyu** [comment]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/8766034/164895697-d0e5c2cd-4cf1-4f3c-8e76-9cf4728cb6d8.png">

https://user-images.githubusercontent.com/8766034/164895749-177a60af-b5e6-49f4-b6d4-4f323f037b7d.mp4

Hi, glad you finally found a solution.However, according to your description, I did not reproduce the abnormal situation you mentioned.Can you provide me with a reproducible demo if it is convenient? thanks.
