### ISSUE TITLE
如何处理在不同界面比如tab加入引导，以及加入引导的时机

### ISSUE THREAD

**Issue by a812358816** [tal-tech/flutter_intro#38]
我这里需求是动态得 获取gloablkey,所以在网络请求之后获取到更新得位置，而且是加载tab上，导致传入全局得context，就是加载到区别的页面上，线上会报 Null check operator used on a null value 问题，还有个问题是出现了关闭不掉
```
 _lastScreenSize = MediaQuery.of(context).size;
```

**Comment by hellohejinyu** [comment]
能提供一个最小复现 demo 嘛，另外针对动态内容，目前确实不太好弄，需要确保 globalKey 绑定的 widget 在渲染出来的前提下再执行引导，否则代码里会找不到这个组件的位置和大小。

**Comment by a812358816** [comment]
这个就是加载在tab上引导图，切换tab，得找到对应位置，还要判断当前widget是不是已经存在

**Comment by hellohejinyu** [comment]
我重写了 3.0 版本，现在通过 `IntroStepBuilder` 来声明需要引导的组件，不需要手动去维护这个糟糕的 keys 了。
