### ISSUE TITLE
[Bug] No dark background in web

### ISSUE THREAD

**Issue by krille-chan** [tal-tech/flutter_intro#7]
First I would like to thank you for this awesome package. It makes creating intros for an app very easy.

I have tried to make an intro for a webapp too. It seems that there is no dark background, so the white text is impossible to read and the "continue" button is nearly impossible to tap.

I'm using the version 0.5.1 of Flutter_intro and Flutter 1.23.0 in Beta channel.

I have a workaround, by just wrapping the widgetbuilder into a container:

```
final Intro roomsPageIntro = Intro(
    stepCount: 6,
    padding: EdgeInsets.all(8),
    borderRadius: BorderRadius.all(Radius.circular(4)),
    widgetBuilder: (step) => Container(
      color: kIsWeb ? Colors.black.withOpacity(0.5) : Colors.transparent,   // Workaround for web
      child: StepWidgetBuilder.useDefaultTheme(
        texts: [
          'Mit dieser Leiste bewegen Sie sich durch die Themen der App.',
          'Hier wählen Sie Unterkategorien zum Thema aus.',
          'Mit diesem Button fügen Sie neue Inhalte hinzu wie: Neue Chats mit Kollegen, neue Patienten, Anfragen, Todos, etc.',
          'Hier finden Sie alle Personen und Gruppen, mit denen Sie persönliche Chats haben.',
          'Hier finden Sie alle Patienten-zentrierten Chats.',
          'Hier finden Sie (bald) Zusatzangebote, wie Chat-Bots oder KI-Analysen.',
        ],
        btnLabel: 'Weiter',
        showStepLabel: true,
      )(step),
    ),
  );
```

**Comment by hellohejinyu** [comment]
Because the ColorFiltered used in the component does not fully support the Web, I want to see what method can be used to solve this problem

**Comment by hellohejinyu** [comment]
https://github.com/flutter/flutter/issues/69849

**Comment by hellohejinyu** [comment]
![image](https://user-images.githubusercontent.com/8766034/111417275-81201a00-8720-11eb-8126-4404a5113586.png)
It's works fine in Flutter 2.0+
